# Generated by Django 2.1 on 2018-09-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('codalternativa', models.IntegerField(db_column='codAlternativa', primary_key=True, serialize=False)),
                ('letraalternativa', models.CharField(blank=True, db_column='letraAlternativa', max_length=100, null=True)),
                ('textoalternativa', models.CharField(blank=True, db_column='textoAlternativa', max_length=100, null=True)),
            ],
            options={
                'db_table': 'alternativa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('codclassificacao', models.AutoField(db_column='codClassificacao', primary_key=True, serialize=False)),
                ('tituloclassificacao', models.CharField(blank=True, db_column='tituloClassificacao', max_length=100, null=True)),
            ],
            options={
                'db_table': 'classificacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('codproblema', models.AutoField(db_column='codProblema', primary_key=True, serialize=False)),
                ('numeroproblema', models.IntegerField(blank=True, db_column='numeroProblema', null=True)),
                ('tituloproblema', models.CharField(blank=True, db_column='tituloProblema', max_length=100, null=True)),
                ('enunciadoproblema', models.CharField(blank=True, db_column='enunciadoProblema', max_length=500, null=True)),
                ('regrasproblema', models.CharField(blank=True, db_column='regrasProblema', max_length=500, null=True)),
                ('imgproblema', models.CharField(blank=True, db_column='imgProblema', default='', max_length=300, null=True)),
                ('classificacao', models.ManyToManyField(blank=True, to='provasobi.Classificacao')),
            ],
            options={
                'db_table': 'problema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('codprova', models.IntegerField(db_column='codProva', primary_key=True, serialize=False)),
                ('anoprova', models.IntegerField(blank=True, db_column='anoProva', null=True)),
                ('nivelprova', models.IntegerField(blank=True, db_column='nivelProva', null=True)),
                ('faseprova', models.IntegerField(blank=True, db_column='faseProva', null=True)),
                ('urlprova', models.URLField(blank=True, db_column='urlProva', default='https://olimpiada.ic.unicamp.br/passadas/', null=True)),
            ],
            options={
                'db_table': 'prova',
                'ordering': ['anoprova'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('codquestao', models.IntegerField(db_column='codQuestao', primary_key=True, serialize=False)),
                ('numeroquestao', models.IntegerField(blank=True, db_column='numeroQuestao', null=True)),
                ('enunciadoquestao', models.CharField(blank=True, db_column='enunciadoQuestao', max_length=100, null=True)),
                ('gabaritoquestao', models.CharField(blank=True, db_column='gabaritoQuestao', max_length=10, null=True)),
                ('codproblema', models.ForeignKey(blank=True, db_column='codProblema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_problemas_questao', to='provasobi.Problema')),
                ('codprova', models.ForeignKey(blank=True, db_column='codProva', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provasobi.Prova')),
            ],
            options={
                'db_table': 'questao',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='problema',
            name='codprova',
            field=models.ForeignKey(blank=True, db_column='codProva', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provasobi.Prova'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='codquestao',
            field=models.ForeignKey(blank=True, db_column='codQuestao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provasobi.Questao'),
        ),
    ]
