# Generated by Django 2.1 on 2018-08-25 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('codalternativa', models.IntegerField(db_column='codAlternativa', primary_key=True, serialize=False)),
                ('letraalternativa', models.CharField(blank=True, db_column='letraAlternativa', max_length=100, null=True)),
                ('textoalternativa', models.CharField(blank=True, db_column='textoAlternativa', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'alternativa',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('codprova', models.IntegerField(db_column='codProva', primary_key=True, serialize=False)),
                ('anoprova', models.IntegerField(blank=True, db_column='anoProva', null=True)),
                ('nivelprova', models.IntegerField(blank=True, db_column='nivelProva', null=True)),
                ('faseprova', models.IntegerField(blank=True, db_column='faseProva', null=True)),
                ('urlprova', models.URLField(blank=True, db_column='urlProva', default='https://olimpiada.ic.unicamp.br/passadas/', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'prova',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('codquestao', models.IntegerField(db_column='codQuestao', primary_key=True, serialize=False)),
                ('numeroquestao', models.IntegerField(blank=True, db_column='numeroQuestao', null=True)),
                ('enunciadoquestao', models.CharField(blank=True, db_column='enunciadoQuestao', max_length=100, null=True)),
                ('codprova', models.ForeignKey(blank=True, db_column='codProva', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provasobi.Prova')),
            ],
            options={
                'managed': True,
                'db_table': 'questao',
            },
        ),
    ]
