# Generated by Django 2.1 on 2018-09-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='codprova',
        ),
        migrations.AddField(
            model_name='questao',
            name='imgquestao',
            field=models.CharField(blank=True, db_column='imgQuestao', default='', max_length=300, null=True),
        ),
    ]
