# Generated by Django 2.1 on 2018-08-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('codclassificacao', models.IntegerField(db_column='codClassificacao', primary_key=True, serialize=False)),
                ('tituloclassificacao', models.CharField(blank=True, db_column='tituloClassificacao', max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'classificacao',
            },
        ),
    ]
