# Generated by Django 2.1 on 2018-08-25 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0002_classificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('codproblema', models.IntegerField(db_column='codProblema', primary_key=True, serialize=False)),
                ('numeroproblema', models.IntegerField(blank=True, db_column='numeroProblema', null=True)),
                ('tituloproblema', models.CharField(blank=True, db_column='tituloProblema', max_length=100, null=True)),
                ('enunciadoproblema', models.CharField(blank=True, db_column='enunciadoProblema', max_length=500, null=True)),
                ('regrasproblema', models.CharField(blank=True, db_column='regrasProblema', max_length=500, null=True)),
                ('codprova', models.ForeignKey(blank=True, db_column='codProva', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provasobi.Prova')),
            ],
            options={
                'db_table': 'problema',
                'managed': True,
            },
        ),
    ]
