# Generated by Django 2.1 on 2018-09-04 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provasobi', '0002_auto_20180902_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvaPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_column='tituloProva', max_length=200, null=True)),
                ('dificuldade', models.IntegerField(blank=True, db_column='dificuldadeProva', null=True)),
                ('observacoes', models.TextField(blank=True, db_column='observacoesProva', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
