# Generated by Django 2.1 on 2018-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0003_auto_20181213_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='codprova',
            field=models.IntegerField(db_column='codProva', primary_key=True, serialize=False),
        ),
    ]
