# Generated by Django 2.1 on 2018-08-26 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0003_problema'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='problemas',
            field=models.ManyToManyField(to='provasobi.Problema'),
        ),
        migrations.AddField(
            model_name='questao',
            name='codproblema',
            field=models.ForeignKey(blank=True, db_column='codProblema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provasobi.Problema'),
        ),
    ]
