# Generated by Django 2.1 on 2018-08-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0004_auto_20180826_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='codclassificacao',
            field=models.AutoField(db_column='codClassificacao', primary_key=True, serialize=False),
        ),
    ]
