# Generated by Django 2.1 on 2018-09-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0004_auto_20180904_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provaperson',
            name='dificuldade',
            field=models.IntegerField(blank=True, db_column='dificuldade', null=True),
        ),
        migrations.AlterField(
            model_name='provaperson',
            name='observacoes',
            field=models.TextField(blank=True, db_column='observacoes', null=True),
        ),
        migrations.AlterField(
            model_name='provaperson',
            name='titulo',
            field=models.CharField(blank=True, db_column='titulo', max_length=200, null=True),
        ),
    ]
