# Generated by Django 2.1 on 2018-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0004_auto_20181213_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='codprova',
            field=models.AutoField(db_column='codProva', primary_key=True, serialize=False),
        ),
    ]
