# Generated by Django 2.1 on 2018-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0005_auto_20180904_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='provaperson',
            name='ano',
            field=models.CharField(blank=True, db_column='ano', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provaperson',
            name='dificuldade',
            field=models.IntegerField(blank=True, db_column='dificuldade', default=0, null=True),
        ),
    ]
