# Generated by Django 2.1 on 2018-12-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0005_auto_20181213_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='codalternativa',
            field=models.AutoField(db_column='codAlternativa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questao',
            name='codquestao',
            field=models.AutoField(db_column='codQuestao', primary_key=True, serialize=False),
        ),
    ]
