# Generated by Django 2.1 on 2018-08-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0005_auto_20180826_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='imgproblema',
            field=models.CharField(blank=True, db_column='imgProblema', default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='problema',
            name='codproblema',
            field=models.AutoField(db_column='codProblema', primary_key=True, serialize=False),
        ),
    ]
