# Generated by Django 2.1 on 2018-08-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0006_auto_20180826_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='gabaritoquestao',
            field=models.CharField(blank=True, db_column='gabaritoQuestao', max_length=10, null=True),
        ),
    ]
