# Generated by Django 2.1 on 2018-12-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0006_auto_20181213_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='urlprova',
            field=models.URLField(blank=True, db_column='urlProva', default='https://olimpiada.ic.unicamp.br/passadas/', null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='prova',
            unique_together={('anoprova', 'faseprova', 'nivelprova')},
        ),
    ]
