# Generated by Django 2.1 on 2018-08-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0007_questao_gabaritoquestao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prova',
            options={'managed': True, 'ordering': ['anoprova']},
        ),
    ]
