# Generated by Django 2.1 on 2018-09-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='professor',
            new_name='usuario',
        ),
    ]
