# Generated by Django 2.1 on 2018-09-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0008_auto_20180910_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usuario',
            new_name='user',
        ),
    ]
