# Generated by Django 2.1 on 2018-09-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0009_auto_20180910_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
