# Generated by Django 2.1 on 2018-09-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0010_auto_20180910_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='provaperson',
            name='questões',
            field=models.ManyToManyField(blank='True', to='provasobi.Questao'),
        ),
    ]
