# Generated by Django 2.1 on 2018-09-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0010_auto_20180910_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provaperson',
            name='ano',
            field=models.CharField(blank=True, db_column='ano', default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provaperson',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Profile'),
        ),
        migrations.AlterField(
            model_name='provaperson',
            name='observacoes',
            field=models.TextField(blank=True, db_column='observacoes', default='', null=True),
        ),
        migrations.AlterField(
            model_name='provaperson',
            name='titulo',
            field=models.CharField(blank=True, db_column='titulo', default='', max_length=200, null=True),
        ),
    ]
