# Generated by Django 2.1 on 2018-09-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0011_auto_20180921_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacao',
            options={'managed': True, 'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
        migrations.AlterModelOptions(
            name='provaperson',
            options={'verbose_name': 'Prova personalizada', 'verbose_name_plural': 'Provas personalizadas'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'managed': True, 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
