# Generated by Django 2.1 on 2018-09-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0011_provaperson_questões'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provaperson',
            old_name='questões',
            new_name='questoes',
        ),
    ]
