# Generated by Django 2.1 on 2018-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0012_auto_20180918_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provaperson',
            name='id',
        ),
        migrations.AddField(
            model_name='provaperson',
            name='codprovaperson',
            field=models.AutoField(db_column='codProvaPerson', default=0, primary_key=True, serialize=False),
        ),
    ]
