# Generated by Django 2.1 on 2018-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0013_auto_20180918_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provaperson',
            name='codprovaperson',
            field=models.AutoField(db_column='codProvaPerson', primary_key=True, serialize=False),
        ),
    ]
