# Generated by Django 2.1 on 2018-10-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0013_provaperson_questoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='provaperson',
            name='codprovaperson',
            field=models.IntegerField(db_column='codProvaPerson', default='0', null=True),
        ),
    ]
