# Generated by Django 2.1 on 2018-09-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0014_auto_20180918_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provaperson',
            name='codprovaperson',
        ),
        migrations.AddField(
            model_name='provaperson',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
