# Generated by Django 2.1 on 2018-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180921_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, default='datetime.date.today', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
