# Generated by Django 2.1 on 2018-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180921_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instituicao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
