# Generated by Django 2.1 on 2018-09-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180921_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Localização'),
        ),
    ]
